### ISSUE TITLE
Nomad Authentication

### ISSUE THREAD

**Issue by jheck90** [axsuul/nomad-event-streamer#4]
Hey!

This tool is simple and great. However, when attempting to implement this in my AWS account, I'm receiving permission denied. We believe this is because we need to be able to pass a nomad auth token with our request. Does this functionality exist and I just don't see it in the `app.rb`? Error and job def below:

## Error
```bash
/usr/local/lib/ruby/3.0.0/json/common.rb:216:in `parse': 809: unexpected token at 'Permission denied' (JSON::ParserError)
	from /usr/local/lib/ruby/3.0.0/json/common.rb:216:in `parse'
	from app.rb:51:in `<main>'
```

## Job Definition
```yaml
job "alerts" {
  datacenters = ["dc1"]
  type        = "service"
  namespace   = "sre"


  group "alerts" {
    count = 1
    network {
      port "http" {
        to = 4646
      }
    }

    task "alerts" {
      driver = "docker"
      config {
        image = "ghcr.io/axsuul/nomad-event-streamer:latest"
        ports = ["http"]
      }

      env {
        SLACK_WEBHOOK_URL = "${SLACK_WEBHOOK_URL}"
        # NOMAD_API_BASE_URL = "http://${attr.unique.network.ip-address}"
        NOMAD_ADDR        = "http://${attr.unique.network.ip-address}:4646"
        # NOMAD_NAMESPACE = "*"
        # TASK_EVENT_TYPE_ALLOWLIST = "Not Restarting,Leader Task Dead,Sibling Task Failed"
      }

      resources {
        cpu    = 75
        memory = 75
      }

     template {
        data        = "{{ with nomadVar \"nomad/jobs/alerts\" }}{{ .Parent.Items | sprig_toJson | parseJSON | toTOML }}{{end}}"
        destination = "${NOMAD_SECRETS_DIR}/env"
        env         = true
      }
      # service {
      #   name = "alerts"
      #   port = "http"
      #   provider = "nomad"
      # }
    }
  }
}

```

**Comment by axsuul** [comment]
Hey thanks for letting me know, yep sorry it wasn't supported yet but I just pushed a PR: https://github.com/axsuul/nomad-event-streamer/pull/5. Can you please give it a try using this image and report back if it works? Thanks!

```
ghcr.io/axsuul/nomad-event-streamer:832eae0ed21f521ad5cf9ea0e363d49835329e41
```

**Comment by jheck90** [comment]
Works great! Thank you so much.
